### ISSUE TITLE
Invalid data

### ISSUE THREAD

**Issue by eightsixtwo** [OrdnanceSurvey/GeoDataViz-Toolkit#1]
Hi,

I've downloaded the three .shp files from the Thematic Mapping Techniques workshop\Data folder and attempted to put them into QGIS.  I've tried adding the files as vector layers using the 'Add Vector Layer' button, and also by dragging & dropping them in, however QGIS throws back an error stating the files are invalid.  I've tried all three files in both 2.18 and 3.0 with the same result.  FYI - I've successfully opened other .shp files in both versions of QGIS without errors, which suggests the files may be corrupt?

Could you advise if the files are OK?

Kind regards

**Comment by charleyglynn** [comment]
Thanks for the feedback. With shapefiles you need to make sure that the accompanying files with the same name (.prj, .dbf, .shx, .qpj) are all in the same folder as the .shp.

Please let me know if this works for you?

Cheers
Charley

**Comment by eightsixtwo** [comment]
Hi, thanks for the response.  I couldn't download some of the files (such as the .prj) as there simply wasn't an option to do so however I managed to get around that by downloading the GitHub desktop app.  I've now got the files and it's worked, thanks very much!

Cheers
Anthony
