### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by davegurnell** [OrdnanceSurvey/GeoDataViz-Toolkit#2]
Hello!

I attended your workshop in Brighton. It was really great -- thank you so much!

FYI -- two links in the README (to Cartographic Design Principles and Cartographic Stylesheets) are broken (at least for me). I get a page with a message like this...

```
The requested URL was rejected. Please consult with your administrator.

Your support ID is: <BIG NUMBER HERE>
```

**Comment by charleyglynn** [comment]
Thanks @davegurnell
