### ISSUE TITLE
OS Icons in SVG format?

### ISSUE THREAD

**Issue by saturdaywalkers** [OrdnanceSurvey/GeoDataViz-Toolkit#4]
Any chance of adding more OS map icons (e.g. pub) in SVG format.
Sure there are lots of SVG libraries out there, but the OS icons, are, well, better

**Comment by egil1978** [comment]
Hi,
Thank you for your comment. We are in the process of creating a new GDV symbol set which will include more of the traditional OS map symbols and a lot more too. It wont be ready for a few months but if you are after some specific symbols right now please let me know and ill get those added as a priority.

**Comment by saturdaywalkers** [comment]
Great news! 
"Public house", Viewpoint, Museum

Many Thanks!

**Comment by egil1978** [comment]
Hi,
The symbols you requested have now been added to the repo.
Any problems let me know.

**Comment by saturdaywalkers** [comment]
Thanks!
