### ISSUE TITLE
Diverging colourmap is colourblind unfriendly

### ISSUE THREAD

**Issue by Fonotec** [OrdnanceSurvey/GeoDataViz-Toolkit#5]
I saw the diverging colourmap from this repository appear in a plot on LinkedIn and I noticed that it not a good colourmap for colourblind people. The combination of using at the same time red and green in a diverging colourmap is problematic for people that have red-green colourblindness (the most common group of colourblindness). 

This is for people with protanopia:
![colourblind2](https://github.com/OrdnanceSurvey/GeoDataViz-Toolkit/assets/1731147/aa48fc61-2c7a-4a79-a0af-9bf09d10a6cb)

and this is for people with deuteranopia:
![colourblind1](https://github.com/OrdnanceSurvey/GeoDataViz-Toolkit/assets/1731147/fbd639cd-62dc-4154-a62a-e50bf9557dd0)

To make it accessible for everyone this colourmap needs to be changed to remove the green-red but change it either to green-blue or red-blue. Currently, for colourblind people it is hard to determine on which side of the diverging colourmap the corresponding colour is.

**Comment by egil1978** [comment]
Hi @Fonotec thank you for the comments. We have now added two CVD friendly diverging palettes.
